# Generated by Django 5.1.2 on 2024-10-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('storage', models.PositiveIntegerField()),
                ('colour', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
