# Generated by Django 5.1.2 on 2024-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='buy_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='buyer_email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='buyer_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='picture',
            field=models.ImageField(null=True, upload_to='mobile-images'),
        ),
    ]
